### PR TITLE
mantis-output

### PR DESCRIPTION
**Pull request by zsxing99**
-fixed result models
-add result view & serializers

### CODE REVIEW

**Review by nickrsan — CHANGES_REQUESTED** [review]
Hi Zesheng - just getting to review these. We'll want to modify the viewset because right now it'll return everyone's results to everyone else - we should limit them to the same user in the queryset. I can do this, but if you have time, please do that as well

**Comment by zsxing99** [comment]
ok, will do an additional filter on the queryset of results

**Comment by zsxing99** [comment]
@nickrsan request fulfilled

**Comment by zsxing99** [comment]
changes were covered and overridden by #15

**Pull request closed without merging**
